ClothingDesigner/Models/ErrorViewModel.cs
namespace ClothingDesigner.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClothingDesigner/Controllers/HomeController.cs
using ClothingDesigner.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ClothingDesigner.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClothingDesigner/Controllers/TasarımController.cs
using Microsoft.AspNetCore.Mvc;

namespace ClothingDesigner.Controllers
{
    public class TasarımController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ClothingDesigner/Views/Home/Index.cshtml
<div class="drag-element">
    <!-- Boyutlandırılacak elementiniz -->
    <!-- xmlnsfarklı XML tabanlı diller arasındaki etiket çakışmaları önler -->
    <svg width=100% height=100% viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg">
        <defs>
            <!-- Burada yuvarlak yolu tanımlıyoruz. -->
            <path id="circlePathCanvas" transform="rotate(90 200 200)" d="M200,200 m-200,0 a200,200 0 1,0 400,0 a200,200 0 1,0 -400,0"></path>
        </defs>
        <path class="path-line" d="M212,200 m-200,0 a188,188 0 1,0 376,0 a188,188 0 1,0 -376,0"
              fill="none" stroke="white" stroke-opacity="0.2" stroke-width="2" />
        <text class="text-path" style="text-anchor: middle;">
            <!-- circlePathCanvas ID'sine sahip yolu kullanıyoruz -->
            <textPath xlink:href="#circlePathCanvas" startOffset="50%">Merhabaaaaa Circle!</textPath>
        </text>
    </svg>
    <i class="bi bi-arrows-angle-expand"></i>
    <i class="bi bi-trash"></i>
    <i class="bi bi-copy"></i>
    <i class="bi bi-arrow-repeat"></i>
</div>

<svg width="100%" height="100%" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <!-- Burada yuvarlak yolu tanımlıyoruz. -->
        <path id="circlePathCanvas" transform="rotate(90 300 300)" d="M300,300 m-300,0 a300,300 0 1,0 600,0 a300,300 0 1,0 -600,0"></path>
    </defs>
    <text class="text-path" style="text-anchor: middle;">
        <!-- circlePathCanvas ID'sine sahip yolu kullanıyoruz -->
        <textPath xlink:href="#circlePathCanvas" startOffset="50%">Merhabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa Circle!</textPath>
    </text>
</svg>

<div class="row col-6">
    <div class="mb-3">
        <label id="TextEditor" class="form-label"></label>
    </div>
    <button id="editText" class="col-6">Edit</button>
    <button id="addText" class="col-6">Add</button>
</div>

<div class="TextEditor">
    <label id="TextEditorr" class="form-label"></label>
</div>

ClothingDesigner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClothingDesigner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClothingDesigner.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.3/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://cdn.quilljs.com/1.3.7/quill.snow.css" />
    <script src='https://unpkg.com/fabric@latest/dist/fabric.js'></script>
    <script src="https://cdn.quilljs.com/1.3.7/quill.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
</head>
<body class="bg-secondary text-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClothingDesigner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link bg-dark text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link bg-dark text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link bg-dark text-light" asp-area="" asp-controller="Tasarım" asp-action="Index">Tasarım</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ClothingDesigner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/7.1.0/tinymce.min.js" integrity="sha512-Va3PZJRSZ8TlnqUfjkA5YPR57+oIscCVoNGjYK1JYsOTw8VU7517hHqs90/h/YuUm8KZl9iD+Dt8K6T8uAJCqw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.3/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="module" src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>jQuery.fn.jquery

ClothingDesigner/Views/Tasarım/Index.cshtml
<div class="drag-element" id="content">
    <!-- Boyutlandırılacak elementiniz -->
    <div class="content">Drag me!</div>
    <i class="bi bi-arrows-angle-expand"></i>
    <i class="bi bi-trash"></i>
    <i class="bi bi-copy"></i>
    <i class="bi bi-arrow-repeat"></i>
</div>

@* <div class="drag-element">
    <!-- Boyutlandırılacak elementiniz -->
    <!-- xmlnsfarklı XML tabanlı diller arasındaki etiket çakışmaları önler -->
    <svg width=100% height=100% viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg">
        <defs>
            <!-- Burada yuvarlak yolu tanımlıyoruz. -->
            <path id="circlePathCanvas" transform="rotate(90 200 200)" d="M200,200 m-200,0 a200,200 0 1,0 400,0 a200,200 0 1,0 -400,0"></path>
        </defs>
        <path class="path-line" d="M212,200 m-200,0 a188,188 0 1,0 376,0 a188,188 0 1,0 -376,0"
              fill="none" stroke="white" stroke-opacity="0.2" stroke-width="2" />
        <text class="text-path" style="text-anchor: middle;">
            <!-- circlePathCanvas ID'sine sahip yolu kullanıyoruz -->
            <textPath xlink:href="#circlePathCanvas" startOffset="50%">Merhabaaaaa Circle!</textPath>
        </text>
    </svg>
    <i class="bi bi-arrows-angle-expand"></i>
    <i class="bi bi-trash"></i>
    <i class="bi bi-copy"></i>
    <i class="bi bi-arrow-repeat"></i>
</div> *@

<div class="drag-element TextEditor">
    <label id="TextEditor" class="form-label"></label>
</div>
<div class="img-container">
    <img src="~/img/beyazön.png" />
    <div class="canvas-container">
        <canvas id="myCanvas" class="canvas-container"></canvas>
    </div>
</div>
<button id="saveBtn">Save State</button>